@extends('frontend.instructor-dashboard.layouts.master')

@section('dashboard-content')
    <div class="modern-meetings-container">
        <!-- Professional Header -->
        <div class="meetings-header">
            <div class="header-content">
                <div class="header-info">
                    <h2 class="page-title">{{ __('Schedule Meetings') }}</h2>
                    <p class="page-subtitle">{{ __('Manage your appointments and meetings with students via Google Meet') }}</p>
                </div>
                <div class="header-actions">
                    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#scheduleMeetingModal">
                        <i class="fas fa-plus me-2"></i>{{ __('Schedule New Meeting') }}
                    </button>
                    <button class="btn btn-outline-primary ms-2" onclick="syncGoogleCalendar()">
                        <i class="fab fa-google me-2"></i>{{ __('Sync Calendar') }}
                    </button>
                </div>
            </div>
        </div>

        <!-- Main Content -->
        <div class="meetings-content">
            <div class="row g-4">
                <!-- Enhanced Calendar View -->
                <div class="col-lg-8">
                    <div class="calendar-section">
                        <div class="calendar-header">
                            <div class="calendar-title">
                                <h4 class="section-title">{{ __('Calendar') }}</h4>
                                <p class="section-subtitle">{{ __('View and manage your scheduled meetings') }}</p>
                            </div>
                            <div class="calendar-nav">
                                <button class="nav-btn" id="prevMonth" title="{{ __('Previous Month') }}">
                                    <i class="fas fa-chevron-left"></i>
                                </button>
                                <span id="currentMonth" class="current-month">{{ now()->format('F Y') }}</span>
                                <button class="nav-btn" id="nextMonth" title="{{ __('Next Month') }}">
                                    <i class="fas fa-chevron-right"></i>
                                </button>
                            </div>
                        </div>
                        
                        <div class="calendar-grid">
                            <div class="calendar-weekdays">
                                <div class="weekday">{{ __('Sun') }}</div>
                                <div class="weekday">{{ __('Mon') }}</div>
                                <div class="weekday">{{ __('Tue') }}</div>
                                <div class="weekday">{{ __('Wed') }}</div>
                                <div class="weekday">{{ __('Thu') }}</div>
                                <div class="weekday">{{ __('Fri') }}</div>
                                <div class="weekday">{{ __('Sat') }}</div>
                            </div>
                            <div class="calendar-days" id="calendarDays">
                                <!-- Calendar days will be generated by JavaScript -->
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Enhanced Upcoming Meetings -->
                <div class="col-lg-4">
                    <div class="upcoming-meetings">
                        <div class="meetings-section-header">
                            <h4 class="section-title">{{ __('Upcoming Meetings') }}</h4>
                            <div class="meetings-filter">
                                <select class="form-select form-select-sm" id="meetingsFilter">
                                    <option value="all">{{ __('All Meetings') }}</option>
                                    <option value="today">{{ __('Today') }}</option>
                                    <option value="week">{{ __('This Week') }}</option>
                                </select>
                            </div>
                        </div>
                        
                        @if($upcomingMeetings->count() > 0)
                            <div class="meetings-list">
                                @foreach($upcomingMeetings as $meeting)
                                    <div class="meeting-item">
                                        <div class="meeting-date">
                                            <div class="date-day">{{ $meeting->date->format('d') }}</div>
                                            <div class="date-month">{{ $meeting->date->format('M') }}</div>
                                        </div>
                                        <div class="meeting-details">
                                            <h6 class="meeting-title">{{ $meeting->title }}</h6>
                                            <p class="meeting-student">{{ __('with') }} {{ $meeting->student_name }}</p>
                                            <div class="meeting-info">
                                                <div class="meeting-time">
                                                    <i class="fas fa-clock me-1"></i>
                                                    {{ $meeting->time }} ({{ $meeting->duration }})
                                                </div>
                                                <div class="meeting-type">
                                                    <i class="fab fa-google me-1"></i>
                                                    {{ __('Google Meet') }}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="meeting-actions">
                                            <button class="action-btn join-btn" onclick="joinGoogleMeet('{{ $meeting->google_meet_link ?? '#' }}')" title="{{ __('Join Google Meet') }}">
                                                <i class="fas fa-video"></i>
                                            </button>
                                            <button class="action-btn edit-btn" onclick="editMeeting('{{ $meeting->id ?? 1 }}')" title="{{ __('Edit Meeting') }}">
                                                <i class="fas fa-edit"></i>
                                            </button>
                                            <button class="action-btn more-btn" onclick="showMeetingOptions('{{ $meeting->id ?? 1 }}')" title="{{ __('More Options') }}">
                                                <i class="fas fa-ellipsis-v"></i>
                                            </button>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        @else
                            <div class="empty-meetings">
                                <div class="empty-icon">
                                    <i class="fas fa-calendar-plus"></i>
                                </div>
                                <h5 class="empty-title">{{ __('No upcoming meetings') }}</h5>
                                <p class="empty-text">{{ __('Schedule your first meeting with a student via Google Meet') }}</p>
                                <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#scheduleMeetingModal">
                                    <i class="fab fa-google me-2"></i>{{ __('Schedule Meeting') }}
                                </button>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>

        <!-- Meeting Statistics -->
        <div class="meetings-stats">
            <div class="row g-4">
                <div class="col-lg-3 col-md-6">
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-calendar-check"></i>
                        </div>
                        <div class="stat-content">
                            <h4>{{ $upcomingMeetings->count() }}</h4>
                            <p>{{ __('Upcoming') }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-clock"></i>
                        </div>
                        <div class="stat-content">
                            <h4>12</h4>
                            <p>{{ __('This Week') }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fab fa-google"></i>
                        </div>
                        <div class="stat-content">
                            <h4>45</h4>
                            <p>{{ __('Google Meet Sessions') }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-chart-line"></i>
                        </div>
                        <div class="stat-content">
                            <h4>98%</h4>
                            <p>{{ __('Attendance Rate') }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Schedule Meeting Modal -->
    <div class="modal fade" id="scheduleMeetingModal" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{ __('Schedule New Meeting') }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <form id="scheduleMeetingForm">
                        <div class="row g-3">
                            <div class="col-md-6">
                                <label class="form-label">{{ __('Meeting Title') }}</label>
                                <input type="text" class="form-control" name="title" required>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label">{{ __('Student') }}</label>
                                <select class="form-select" name="student_id" required>
                                    <option value="">{{ __('Select Student') }}</option>
                                    <option value="1">John Doe</option>
                                    <option value="2">Jane Smith</option>
                                    <option value="3">Mike Johnson</option>
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label">{{ __('Date') }}</label>
                                <input type="date" class="form-control" name="date" required>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label">{{ __('Time') }}</label>
                                <input type="time" class="form-control" name="time" required>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label">{{ __('Duration') }}</label>
                                <select class="form-select" name="duration" required>
                                    <option value="15">15 {{ __('minutes') }}</option>
                                    <option value="30" selected>30 {{ __('minutes') }}</option>
                                    <option value="45">45 {{ __('minutes') }}</option>
                                    <option value="60">1 {{ __('hour') }}</option>
                                    <option value="90">1.5 {{ __('hours') }}</option>
                                    <option value="120">2 {{ __('hours') }}</option>
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label">{{ __('Meeting Type') }}</label>
                                <select class="form-select" name="type" required>
                                    <option value="video_call">{{ __('Video Call') }}</option>
                                    <option value="phone_call">{{ __('Phone Call') }}</option>
                                    <option value="in_person">{{ __('In Person') }}</option>
                                </select>
                            </div>
                            <div class="col-12">
                                <label class="form-label">{{ __('Description') }}</label>
                                <textarea class="form-control" name="description" rows="3" placeholder="{{ __('Meeting agenda or notes...') }}"></textarea>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ __('Cancel') }}</button>
                    <button type="button" class="btn btn-primary" onclick="scheduleMeeting()">{{ __('Schedule Meeting') }}</button>
                </div>
            </div>
        </div>
    </div>

    <style>
        .modern-meetings-container {
            background: white;
            border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
            overflow: hidden;
        }

        .meetings-header {
            background: white;
            border-bottom: 1px solid #e2e8f0;
            padding: 24px 32px;
        }

        .header-content {
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-wrap: wrap;
            gap: 16px;
        }

        .page-title {
            font-size: 24px;
            font-weight: 700;
            color: #1f2937;
            margin: 0;
        }

        .page-subtitle {
            color: #6b7280;
            margin: 4px 0 0 0;
            font-size: 14px;
        }

        .header-actions {
            display: flex;
            gap: 12px;
            flex-wrap: wrap;
        }

        .header-actions .btn {
            border-radius: 6px;
            padding: 10px 20px;
            font-weight: 500;
            transition: all 0.2s ease;
        }

        .header-actions .btn-primary {
            background: #3b82f6;
            border: none;
        }

        .header-actions .btn-primary:hover {
            background: #2563eb;
            transform: translateY(-1px);
        }

        .header-actions .btn-outline-primary {
            border-color: #3b82f6;
            color: #3b82f6;
        }

        .header-actions .btn-outline-primary:hover {
            background: #3b82f6;
            border-color: #3b82f6;
            color: white;
        }

        .meetings-content {
            padding: 24px 32px;
            background: #f8f9fa;
        }

        .calendar-section {
            background: white;
            padding: 24px;
            border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
        }

        .calendar-header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-bottom: 24px;
            flex-wrap: wrap;
            gap: 16px;
        }

        .section-title {
            font-size: 18px;
            font-weight: 600;
            color: #1f2937;
            margin: 0;
        }

        .section-subtitle {
            color: #6b7280;
            font-size: 14px;
            margin: 4px 0 0 0;
        }

        .calendar-nav {
            display: flex;
            align-items: center;
            gap: 12px;
        }

        .nav-btn {
            background: white;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            padding: 8px 12px;
            color: #374151;
            transition: all 0.2s ease;
            cursor: pointer;
        }

        .nav-btn:hover {
            background: #f9fafb;
            border-color: #3b82f6;
            color: #3b82f6;
        }

        .current-month {
            font-weight: 600;
            color: #1f2937;
            font-size: 16px;
        }

        .calendar-grid {
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            overflow: hidden;
        }

        .calendar-weekdays {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
            background: #f8f9fa;
        }

        .weekday {
            padding: 15px;
            text-align: center;
            font-weight: 600;
            color: #6c757d;
            border-right: 1px solid #e9ecef;
        }

        .weekday:last-child {
            border-right: none;
        }

        .calendar-days {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
        }

        .calendar-day {
            min-height: 80px;
            padding: 10px;
            border-right: 1px solid #e9ecef;
            border-bottom: 1px solid #e9ecef;
            cursor: pointer;
            transition: background-color 0.3s ease;
            position: relative;
        }

        .calendar-day:hover {
            background: #f8f9fa;
        }

        .calendar-day.other-month {
            color: #adb5bd;
            background: #f8f9fa;
        }

        .calendar-day.today {
            background: #3b82f6;
            color: white;
        }

        .calendar-day.has-meeting {
            background: rgba(59, 130, 246, 0.1);
        }

        .calendar-day.has-meeting::after {
            content: '';
            position: absolute;
            bottom: 5px;
            right: 5px;
            width: 8px;
            height: 8px;
            background: #3b82f6;
            border-radius: 50%;
        }

        .upcoming-meetings {
            background: white;
            padding: 24px;
            border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
            height: fit-content;
        }

        .meetings-section-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
            flex-wrap: wrap;
            gap: 12px;
        }

        .meetings-filter .form-select {
            border-radius: 6px;
            border: 1px solid #e2e8f0;
            font-size: 13px;
            padding: 6px 12px;
        }

        .meetings-list {
            max-height: 500px;
            overflow-y: auto;
        }

        .meeting-item {
            display: flex;
            align-items: flex-start;
            gap: 16px;
            padding: 16px;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            margin-bottom: 12px;
            transition: all 0.2s ease;
        }

        .meeting-item:hover {
            border-color: #3b82f6;
            box-shadow: 0 2px 8px rgba(59, 130, 246, 0.1);
        }

        .meeting-date {
            background: #f3f4f6;
            border-radius: 8px;
            padding: 12px;
            text-align: center;
            min-width: 60px;
        }

        .date-day {
            font-size: 18px;
            font-weight: 700;
            color: #1f2937;
            line-height: 1;
        }

        .date-month {
            font-size: 12px;
            color: #6b7280;
            text-transform: uppercase;
            font-weight: 500;
            margin-top: 2px;
        }

        .meeting-details {
            flex: 1;
            min-width: 0;
        }

        .meeting-title {
            font-size: 14px;
            font-weight: 600;
            color: #1f2937;
            margin: 0 0 4px 0;
        }

        .meeting-student {
            font-size: 13px;
            color: #6b7280;
            margin: 0 0 8px 0;
        }

        .meeting-info {
            display: flex;
            flex-direction: column;
            gap: 4px;
        }

        .meeting-time,
        .meeting-type {
            font-size: 12px;
            color: #6b7280;
            display: flex;
            align-items: center;
        }

        .meeting-type i {
            color: #4285f4;
        }

        .meeting-actions {
            display: flex;
            gap: 6px;
            flex-shrink: 0;
        }

        .action-btn {
            background: white;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            padding: 8px;
            color: #6b7280;
            transition: all 0.2s ease;
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .action-btn:hover {
            border-color: #3b82f6;
            color: #3b82f6;
        }

        .join-btn:hover {
            background: #dbeafe;
            border-color: #3b82f6;
            color: #1d4ed8;
        }

        .edit-btn:hover {
            background: #f3f4f6;
            border-color: #6b7280;
            color: #374151;
        }

        .empty-meetings {
            text-align: center;
            padding: 40px 20px;
        }

        .empty-icon {
            width: 80px;
            height: 80px;
            background: #f3f4f6;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0 auto 20px;
        }

        .empty-icon i {
            font-size: 32px;
            color: #9ca3af;
        }

        .empty-title {
            font-size: 18px;
            font-weight: 600;
            color: #374151;
            margin-bottom: 8px;
        }

        .empty-text {
            color: #6b7280;
            font-size: 14px;
            margin-bottom: 20px;
            line-height: 1.5;
        }

        .meetings-stats {
            margin-top: 24px;
        }

        .stat-card {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            display: flex;
            align-items: center;
            gap: 16px;
            transition: all 0.2s ease;
        }

        .stat-card:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
        }

        .stat-icon {
            width: 48px;
            height: 48px;
            background: #f3f4f6;
            border-radius: 8px;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #3b82f6;
            font-size: 20px;
        }

        .stat-content h4 {
            font-size: 24px;
            font-weight: 700;
            color: #1f2937;
            margin: 0;
        }

        .stat-content p {
            font-size: 14px;
            color: #6b7280;
            margin: 2px 0 0 0;
        }

        /* Modal Styling */
        .modal-content {
            border-radius: 8px;
            border: none;
            box-shadow: 0 10px 30px rgba(0,0,0,0.15);
        }

        .modal-header {
            background: #f8f9fa;
            border-bottom: 1px solid #e2e8f0;
            border-radius: 8px 8px 0 0;
            padding: 20px 24px;
        }

        .modal-title {
            font-weight: 600;
            color: #1f2937;
        }

        .modal-body {
            padding: 24px;
        }

        .modal-footer {
            background: #f8f9fa;
            border-top: 1px solid #e2e8f0;
            border-radius: 0 0 8px 8px;
            padding: 16px 24px;
        }

        .form-label {
            font-weight: 500;
            color: #374151;
            margin-bottom: 6px;
        }

        .form-control,
        .form-select {
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            padding: 10px 12px;
            transition: all 0.2s ease;
        }

        .form-control:focus,
        .form-select:focus {
            border-color: #3b82f6;
            box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
        }

        .btn-primary {
            background: #3b82f6;
            border-color: #3b82f6;
            border-radius: 6px;
            padding: 10px 20px;
            font-weight: 500;
        }

        .btn-primary:hover {
            background: #2563eb;
            border-color: #2563eb;
        }

        .btn-secondary {
            background: #6b7280;
            border-color: #6b7280;
            border-radius: 6px;
            padding: 10px 20px;
            font-weight: 500;
        }

        .btn-secondary:hover {
            background: #4b5563;
            border-color: #4b5563;
        }

        /* Responsive Design */
        @media (max-width: 768px) {
            .modern-meetings-container {
                padding: 16px;
            }

            .meetings-header {
                flex-direction: column;
                align-items: flex-start;
                gap: 16px;
            }

            .header-actions {
                width: 100%;
                justify-content: flex-start;
            }

            .meetings-content {
                flex-direction: column;
            }

            .calendar-section,
            .upcoming-meetings {
                margin-bottom: 20px;
            }

            .meeting-item {
                flex-direction: column;
                align-items: flex-start;
                gap: 12px;
            }

            .meeting-actions {
                width: 100%;
                justify-content: flex-end;
            }
        }

        .date-day {
            font-size: 24px;
            font-weight: 700;
            color: #6777ef;
            line-height: 1;
        }

        .date-month {
            font-size: 12px;
            color: #6c757d;
            text-transform: uppercase;
        }

        .meeting-details {
            flex: 1;
        }

        .meeting-title {
            font-weight: 600;
            margin-bottom: 5px;
            color: #2c3e50;
        }

        .meeting-student {
            color: #6c757d;
            font-size: 14px;
            margin-bottom: 5px;
        }

        .meeting-time,
        .meeting-type {
            font-size: 13px;
            color: #6c757d;
            margin-bottom: 2px;
        }

        .meeting-actions {
            display: flex;
            flex-direction: column;
            gap: 5px;
        }

        .stat-card-small {
            background: white;
            padding: 20px;
            border-radius: 12px;
            box-shadow: 0 5px 15px rgba(0,0,0,0.1);
            text-align: center;
            transition: transform 0.3s ease;
        }

        .stat-card-small:hover {
            transform: translateY(-3px);
        }

        .stat-card-small .stat-icon {
            width: 50px;
            height: 50px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            border-radius: 12px;
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            font-size: 20px;
            margin: 0 auto 15px;
        }

        .stat-card-small h4 {
            font-size: 2rem;
            font-weight: 700;
            margin-bottom: 5px;
            color: #2c3e50;
        }

        .stat-card-small p {
            color: #6c757d;
            margin: 0;
            font-weight: 500;
        }

        .empty-meetings {
            border: 2px dashed #e9ecef;
            border-radius: 10px;
        }

        @media (max-width: 768px) {
            .calendar-day {
                min-height: 60px;
                padding: 5px;
                font-size: 14px;
            }
            
            .meeting-item {
                flex-direction: column;
                text-align: center;
            }
            
            .meeting-date {
                margin-right: 0;
                margin-bottom: 10px;
            }
            
            .meeting-actions {
                flex-direction: row;
                justify-content: center;
                margin-top: 10px;
            }
        }
    </style>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            generateCalendar();
            
            // Calendar navigation
            document.getElementById('prevMonth').addEventListener('click', function() {
                // Previous month logic
                console.log('Previous month');
            });
            
            document.getElementById('nextMonth').addEventListener('click', function() {
                // Next month logic
                console.log('Next month');
            });
        });

        function generateCalendar() {
            const calendarDays = document.getElementById('calendarDays');
            const today = new Date();
            const currentMonth = today.getMonth();
            const currentYear = today.getFullYear();
            
            // Get first day of month and number of days
            const firstDay = new Date(currentYear, currentMonth, 1).getDay();
            const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();
            const daysInPrevMonth = new Date(currentYear, currentMonth, 0).getDate();
            
            let html = '';
            
            // Previous month days
            for (let i = firstDay - 1; i >= 0; i--) {
                html += `<div class="calendar-day other-month">${daysInPrevMonth - i}</div>`;
            }
            
            // Current month days
            for (let day = 1; day <= daysInMonth; day++) {
                const isToday = day === today.getDate() && currentMonth === today.getMonth() && currentYear === today.getFullYear();
                const hasMeeting = [5, 12, 18, 25].includes(day); // Sample meeting days
                
                let classes = 'calendar-day';
                if (isToday) classes += ' today';
                if (hasMeeting) classes += ' has-meeting';
                
                html += `<div class="${classes}" onclick="selectDate(${day})">${day}</div>`;
            }
            
            // Next month days to fill the grid
            const totalCells = Math.ceil((firstDay + daysInMonth) / 7) * 7;
            const remainingCells = totalCells - (firstDay + daysInMonth);
            
            for (let day = 1; day <= remainingCells; day++) {
                html += `<div class="calendar-day other-month">${day}</div>`;
            }
            
            calendarDays.innerHTML = html;
        }

        function selectDate(day) {
            // Set the selected date in the modal form
            const today = new Date();
            const selectedDate = new Date(today.getFullYear(), today.getMonth(), day);
            const dateInput = document.querySelector('input[name="date"]');
            if (dateInput) {
                dateInput.value = selectedDate.toISOString().split('T')[0];
            }
            
            // Open the schedule modal
            const modal = new bootstrap.Modal(document.getElementById('scheduleMeetingModal'));
            modal.show();
        }

        function scheduleMeeting() {
            const form = document.getElementById('scheduleMeetingForm');
            const formData = new FormData(form);
            
            // Here you would normally send the data to your backend
            console.log('Scheduling meeting:', Object.fromEntries(formData));
            
            // Show success message
            alert('Meeting scheduled successfully!');
            
            // Close modal
            const modal = bootstrap.Modal.getInstance(document.getElementById('scheduleMeetingModal'));
            modal.hide();
            
            // Reset form
            form.reset();
        }

        function joinMeeting(meetingId) {
            alert(`Joining meeting ${meetingId}...`);
            // Here you would integrate with your video calling solution
        }

        function editMeeting(meetingId) {
            alert(`Editing meeting ${meetingId}...`);
            // Here you would open an edit modal with the meeting details
        }
    </script>
@endsection