@extends('frontend.student-dashboard.layouts.master')

@section('title', 'My Meetings')

@section('dashboard-content')
    <div class="modern-meetings-container">
        <!-- Professional Header -->
        <div class="meetings-header">
            <div class="header-content">
                <div class="header-info">
                    <h2 class="page-title">{{ __('My Meetings') }}</h2>
                    <p class="page-subtitle">{{ __('View and join your scheduled meetings with instructors') }}</p>
                </div>
                <div class="header-actions">
                    <button class="btn btn-outline-primary" id="syncBtn">
                        <i class="fas fa-sync-alt me-2"></i>{{ __('Sync Calendar') }}
                    </button>
                    <button class="btn btn-primary" id="requestMeetingBtn">
                        <i class="fas fa-plus me-2"></i>{{ __('Request Meeting') }}
                    </button>
                </div>
            </div>
        </div>

        <!-- Main Content -->
        <div class="meetings-content">
            <div class="row g-4">
                <!-- Enhanced Calendar View -->
                <div class="col-lg-8">
                    <div class="calendar-container">
                        <div class="calendar-header">
                            <div class="calendar-nav">
                                <button class="nav-btn" id="prevMonth">
                                    <i class="fas fa-chevron-left"></i>
                                </button>
                                <h4 class="current-month" id="currentMonth">{{ now()->format('F Y') }}</h4>
                                <button class="nav-btn" id="nextMonth">
                                    <i class="fas fa-chevron-right"></i>
                                </button>
                            </div>
                            <div class="view-toggle">
                                <button class="toggle-btn active" data-view="month">{{ __('Month') }}</button>
                                <button class="toggle-btn" data-view="week">{{ __('Week') }}</button>
                            </div>
                        </div>
                        
                        <div class="calendar-grid">
                            <div class="calendar-weekdays">
                                <div class="weekday">{{ __('Sun') }}</div>
                                <div class="weekday">{{ __('Mon') }}</div>
                                <div class="weekday">{{ __('Tue') }}</div>
                                <div class="weekday">{{ __('Wed') }}</div>
                                <div class="weekday">{{ __('Thu') }}</div>
                                <div class="weekday">{{ __('Fri') }}</div>
                                <div class="weekday">{{ __('Sat') }}</div>
                            </div>
                            <div class="calendar-days" id="calendarDays">
                                <!-- Calendar days will be generated by JavaScript -->
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Upcoming Meetings -->
                <div class="col-lg-4">
                    <div class="upcoming-meetings">
                        <div class="section-header">
                            <h5 class="section-title">{{ __('Upcoming Meetings') }}</h5>
                            <span class="meeting-count">{{ count($upcomingMeetings) }}</span>
                        </div>
                        
                        <div class="meetings-list">
                            @forelse($upcomingMeetings as $meeting)
                                <div class="meeting-item" data-meeting-id="{{ $meeting['id'] }}">
                                    <div class="meeting-time">
                                        <div class="time-info">
                                            <span class="date">{{ \Carbon\Carbon::parse($meeting['date'])->format('M d') }}</span>
                                            <span class="time">{{ $meeting['time'] }}</span>
                                        </div>
                                    </div>
                                    <div class="meeting-details">
                                        <h6 class="meeting-title">{{ $meeting['title'] }}</h6>
                                        <p class="meeting-course">{{ $meeting['course'] }}</p>
                                        <div class="meeting-instructor">
                                            <div class="instructor-avatar">
                                                @if($meeting['instructor_image'])
                                                    <img src="{{ asset($meeting['instructor_image']) }}" alt="{{ $meeting['instructor'] }}">
                                                @else
                                                    <div class="avatar-placeholder">
                                                        {{ substr($meeting['instructor'], 0, 1) }}
                                                    </div>
                                                @endif
                                            </div>
                                            <span class="instructor-name">{{ $meeting['instructor'] }}</span>
                                        </div>
                                    </div>
                                    <div class="meeting-actions">
                                        @if($meeting['meeting_link'])
                                            <a href="{{ $meeting['meeting_link'] }}" target="_blank" class="action-btn join-btn" title="{{ __('Join Meeting') }}">
                                                <i class="fas fa-video"></i>
                                            </a>
                                        @endif
                                        <button class="action-btn info-btn" title="{{ __('Meeting Info') }}" onclick="showMeetingInfo({{ json_encode($meeting) }})">
                                            <i class="fas fa-info"></i>
                                        </button>
                                    </div>
                                </div>
                            @empty
                                <div class="empty-state">
                                    <div class="empty-icon">
                                        <i class="fas fa-calendar-times"></i>
                                    </div>
                                    <h6 class="empty-title">{{ __('No upcoming meetings') }}</h6>
                                    <p class="empty-text">{{ __('You don\'t have any scheduled meetings yet.') }}</p>
                                    <button class="btn btn-primary btn-sm" id="requestMeetingBtn2">
                                        {{ __('Request Meeting') }}
                                    </button>
                                </div>
                            @endforelse
                        </div>
                    </div>
                </div>
            </div>

            <!-- Meetings Statistics -->
            <div class="row g-4 mt-4">
                <div class="col-lg-3 col-md-6">
                    <div class="stat-card">
                        <div class="stat-icon upcoming">
                            <i class="fas fa-clock"></i>
                        </div>
                        <div class="stat-info">
                            <h4 class="stat-number">{{ count($upcomingMeetings) }}</h4>
                            <p class="stat-label">{{ __('Upcoming Meetings') }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="stat-card">
                        <div class="stat-icon weekly">
                            <i class="fas fa-calendar-week"></i>
                        </div>
                        <div class="stat-info">
                            <h4 class="stat-number">{{ collect($upcomingMeetings)->filter(function($meeting) { return \Carbon\Carbon::parse($meeting['date'])->isCurrentWeek(); })->count() }}</h4>
                            <p class="stat-label">{{ __('This Week') }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="stat-card">
                        <div class="stat-icon google-meet">
                            <i class="fab fa-google"></i>
                        </div>
                        <div class="stat-info">
                            <h4 class="stat-number">{{ collect($upcomingMeetings)->filter(function($meeting) { return !empty($meeting['meeting_link']); })->count() }}</h4>
                            <p class="stat-label">{{ __('Google Meet Sessions') }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="stat-card">
                        <div class="stat-icon courses">
                            <i class="fas fa-graduation-cap"></i>
                        </div>
                        <div class="stat-info">
                            <h4 class="stat-number">{{ collect($upcomingMeetings)->pluck('course')->unique()->count() }}</h4>
                            <p class="stat-label">{{ __('Active Courses') }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Request Meeting Modal -->
    <div class="modal fade" id="requestMeetingModal" tabindex="-1" aria-labelledby="requestMeetingModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="requestMeetingModalLabel">{{ __('Request Meeting') }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="requestMeetingForm">
                        <div class="row g-3">
                            <div class="col-12">
                                <label for="meetingTitle" class="form-label">{{ __('Meeting Title') }}</label>
                                <input type="text" class="form-control" id="meetingTitle" placeholder="{{ __('Enter meeting title') }}" required>
                            </div>
                            <div class="col-md-6">
                                <label for="instructorSelect" class="form-label">{{ __('Select Instructor') }}</label>
                                <select class="form-select" id="instructorSelect" required>
                                    <option value="">{{ __('Choose instructor...') }}</option>
                                    @if(isset($enrolledCourses))
                                        @foreach($enrolledCourses as $course)
                                            @if($course->instructor)
                                                <option value="{{ $course->instructor->id }}">{{ $course->instructor->name }}</option>
                                            @endif
                                        @endforeach
                                    @endif
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label for="courseSelect" class="form-label">{{ __('Related Course') }}</label>
                                <select class="form-select" id="courseSelect" required>
                                    <option value="">{{ __('Choose course...') }}</option>
                                    @if(isset($enrolledCourses))
                                        @foreach($enrolledCourses as $course)
                                            <option value="{{ $course->id }}">{{ $course->title }}</option>
                                        @endforeach
                                    @endif
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label for="meetingDate" class="form-label">{{ __('Preferred Date') }}</label>
                                <input type="date" class="form-control" id="meetingDate" min="{{ now()->format('Y-m-d') }}" required>
                            </div>
                            <div class="col-md-6">
                                <label for="meetingTime" class="form-label">{{ __('Preferred Time') }}</label>
                                <input type="time" class="form-control" id="meetingTime" required>
                            </div>
                            <div class="col-md-6">
                                <label for="meetingDuration" class="form-label">{{ __('Duration (minutes)') }}</label>
                                <select class="form-select" id="meetingDuration" required>
                                    <option value="30">30 {{ __('minutes') }}</option>
                                    <option value="60" selected>60 {{ __('minutes') }}</option>
                                    <option value="90">90 {{ __('minutes') }}</option>
                                    <option value="120">120 {{ __('minutes') }}</option>
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label for="meetingType" class="form-label">{{ __('Meeting Type') }}</label>
                                <select class="form-select" id="meetingType" required>
                                    <option value="google_meet">{{ __('Google Meet') }}</option>
                                    <option value="zoom">{{ __('Zoom') }}</option>
                                    <option value="teams">{{ __('Microsoft Teams') }}</option>
                                </select>
                            </div>
                            <div class="col-12">
                                <label for="meetingDescription" class="form-label">{{ __('Meeting Description') }}</label>
                                <textarea class="form-control" id="meetingDescription" rows="3" placeholder="{{ __('Describe the purpose of this meeting...') }}"></textarea>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ __('Cancel') }}</button>
                    <button type="button" class="btn btn-primary" id="submitMeetingRequest">{{ __('Send Request') }}</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Meeting Info Modal -->
    <div class="modal fade" id="meetingInfoModal" tabindex="-1" aria-labelledby="meetingInfoModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="meetingInfoModalLabel">{{ __('Meeting Details') }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="meetingInfoContent">
                    <!-- Meeting details will be populated by JavaScript -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ __('Close') }}</button>
                    <button type="button" class="btn btn-primary" id="joinMeetingFromModal">{{ __('Join Meeting') }}</button>
                </div>
            </div>
        </div>
    </div>

    <style>
        .modern-meetings-container {
            background: white;
            border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
            overflow: hidden;
        }

        .meetings-header {
            background: white;
            border-bottom: 1px solid #e2e8f0;
            padding: 24px 32px;
        }

        .header-content {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .page-title {
            font-size: 24px;
            font-weight: 700;
            color: #1f2937;
            margin: 0;
        }

        .page-subtitle {
            color: #6b7280;
            margin: 4px 0 0 0;
            font-size: 14px;
        }

        .header-actions {
            display: flex;
            gap: 12px;
        }

        .header-actions .btn {
            border-radius: 6px;
            padding: 10px 20px;
            font-weight: 500;
            transition: all 0.2s ease;
        }

        .meetings-content {
            padding: 32px;
        }

        .calendar-container {
            background: white;
            border-radius: 8px;
            border: 1px solid #e2e8f0;
            overflow: hidden;
        }

        .calendar-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 20px 24px;
            border-bottom: 1px solid #e2e8f0;
            background: #f8fafc;
        }

        .calendar-nav {
            display: flex;
            align-items: center;
            gap: 16px;
        }

        .nav-btn {
            background: none;
            border: 1px solid #d1d5db;
            border-radius: 6px;
            width: 36px;
            height: 36px;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #6b7280;
            cursor: pointer;
            transition: all 0.2s ease;
        }

        .nav-btn:hover {
            background: #f3f4f6;
            border-color: #9ca3af;
        }

        .current-month {
            font-size: 18px;
            font-weight: 600;
            color: #1f2937;
            margin: 0;
            min-width: 150px;
            text-align: center;
        }

        .view-toggle {
            display: flex;
            background: #f1f5f9;
            border-radius: 6px;
            padding: 2px;
        }

        .toggle-btn {
            background: none;
            border: none;
            padding: 8px 16px;
            border-radius: 4px;
            font-size: 14px;
            font-weight: 500;
            color: #64748b;
            cursor: pointer;
            transition: all 0.2s ease;
        }

        .toggle-btn.active {
            background: white;
            color: #1f2937;
            box-shadow: 0 1px 2px rgba(0,0,0,0.1);
        }

        .calendar-grid {
            padding: 0;
        }

        .calendar-weekdays {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
            background: #f8fafc;
            border-bottom: 1px solid #e2e8f0;
        }

        .weekday {
            padding: 12px;
            text-align: center;
            font-weight: 600;
            color: #6b7280;
            font-size: 13px;
            text-transform: uppercase;
        }

        .calendar-days {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
            min-height: 300px;
        }

        .calendar-day {
            border-right: 1px solid #f1f5f9;
            border-bottom: 1px solid #f1f5f9;
            padding: 8px;
            min-height: 80px;
            position: relative;
            cursor: pointer;
            transition: background-color 0.2s ease;
        }

        .calendar-day:hover {
            background: #f8fafc;
        }

        .calendar-day.other-month {
            color: #d1d5db;
            background: #fafafa;
        }

        .calendar-day.today {
            background: #eff6ff;
            border-color: #3b82f6;
        }

        .day-number {
            font-weight: 500;
            color: #1f2937;
            margin-bottom: 4px;
        }

        .day-meetings {
            display: flex;
            flex-direction: column;
            gap: 2px;
        }

        .meeting-dot {
            width: 100%;
            height: 4px;
            background: #3b82f6;
            border-radius: 2px;
            font-size: 10px;
            color: white;
            text-align: center;
            line-height: 1;
        }

        .upcoming-meetings {
            background: white;
            border-radius: 8px;
            border: 1px solid #e2e8f0;
            height: fit-content;
        }

        .section-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 20px 24px;
            border-bottom: 1px solid #e2e8f0;
            background: #f8fafc;
        }

        .section-title {
            font-weight: 600;
            color: #1f2937;
            margin: 0;
        }

        .meeting-count {
            background: #3b82f6;
            color: white;
            padding: 4px 8px;
            border-radius: 12px;
            font-size: 12px;
            font-weight: 500;
        }

        .meetings-list {
            padding: 0;
            max-height: 400px;
            overflow-y: auto;
        }

        .empty-state {
            text-align: center;
            padding: 40px 20px;
        }

        .empty-icon {
            font-size: 48px;
            color: #d1d5db;
            margin-bottom: 16px;
        }

        .empty-title {
            font-weight: 600;
            color: #1f2937;
            margin-bottom: 8px;
        }

        .empty-text {
            color: #6b7280;
            margin-bottom: 16px;
        }

        .stat-card {
            background: white;
            border-radius: 8px;
            border: 1px solid #e2e8f0;
            padding: 24px;
            display: flex;
            align-items: center;
            gap: 16px;
            transition: all 0.2s ease;
        }

        .stat-card:hover {
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
            transform: translateY(-2px);
        }

        .stat-icon {
            width: 48px;
            height: 48px;
            border-radius: 8px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 20px;
            color: white;
        }

        .stat-icon.upcoming {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        }

        .stat-icon.weekly {
            background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
        }

        .stat-icon.google-meet {
            background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
        }

        .stat-icon.courses {
            background: linear-gradient(135deg, #43e97b 0%, #38f9d7 100%);
        }

        .stat-number {
            font-size: 24px;
            font-weight: 700;
            color: #1f2937;
            margin: 0 0 4px 0;
        }

        .stat-label {
            color: #6b7280;
            margin: 0;
            font-size: 14px;
        }

        /* Responsive Design */
        @media (max-width: 768px) {
            .header-content {
                flex-direction: column;
                gap: 16px;
                align-items: stretch;
            }

            .header-actions {
                justify-content: center;
            }

            .meetings-content {
                padding: 16px;
            }

            .calendar-header {
                flex-direction: column;
                gap: 16px;
            }

            .calendar-nav {
                justify-content: center;
            }

            .calendar-day {
                min-height: 60px;
                padding: 4px;
            }
        }
    </style>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Calendar functionality
            const currentMonthElement = document.getElementById('currentMonth');
            const calendarDays = document.getElementById('calendarDays');
            const prevMonthBtn = document.getElementById('prevMonth');
            const nextMonthBtn = document.getElementById('nextMonth');
            
            let currentDate = new Date();
            
            function generateCalendar(year, month) {
                const firstDay = new Date(year, month, 1);
                const lastDay = new Date(year, month + 1, 0);
                const startDate = new Date(firstDay);
                startDate.setDate(startDate.getDate() - firstDay.getDay());
                
                currentMonthElement.textContent = firstDay.toLocaleDateString('en-US', { 
                    month: 'long', 
                    year: 'numeric' 
                });
                
                calendarDays.innerHTML = '';
                
                for (let i = 0; i < 42; i++) {
                    const date = new Date(startDate);
                    date.setDate(startDate.getDate() + i);
                    
                    const dayElement = document.createElement('div');
                    dayElement.className = 'calendar-day';
                    
                    if (date.getMonth() !== month) {
                        dayElement.classList.add('other-month');
                    }
                    
                    if (date.toDateString() === new Date().toDateString()) {
                        dayElement.classList.add('today');
                    }
                    
                    dayElement.innerHTML = `
                        <div class="day-number">${date.getDate()}</div>
                        <div class="day-meetings">
                            ${Math.random() > 0.8 ? '<div class="meeting-dot"></div>' : ''}
                        </div>
                    `;
                    
                    calendarDays.appendChild(dayElement);
                }
            }
            
            prevMonthBtn.addEventListener('click', function() {
                currentDate.setMonth(currentDate.getMonth() - 1);
                generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
            });
            
            nextMonthBtn.addEventListener('click', function() {
                currentDate.setMonth(currentDate.getMonth() + 1);
                generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
            });
            
            // Initialize calendar
            generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
            
            // Request meeting modal
            const requestMeetingBtns = document.querySelectorAll('#requestMeetingBtn, #requestMeetingBtn2');
            const requestMeetingModal = new bootstrap.Modal(document.getElementById('requestMeetingModal'));
            
            requestMeetingBtns.forEach(btn => {
                btn.addEventListener('click', function() {
                    requestMeetingModal.show();
                });
            });
            
            // Submit meeting request
            document.getElementById('submitMeetingRequest').addEventListener('click', function() {
                const form = document.getElementById('requestMeetingForm');
                if (form.checkValidity()) {
                    // Here you would normally send the request to the server
                    alert('Meeting request sent successfully! Your instructor will be notified.');
                    requestMeetingModal.hide();
                    form.reset();
                } else {
                    form.reportValidity();
                }
            });
            
            // Sync calendar
            document.getElementById('syncBtn').addEventListener('click', function() {
                this.innerHTML = '<i class="fas fa-spinner fa-spin me-2"></i>{{ __("Syncing...") }}';
                setTimeout(() => {
                    this.innerHTML = '<i class="fas fa-sync-alt me-2"></i>{{ __("Sync Calendar") }}';
                    alert('Calendar synced successfully!');
                }, 2000);
            });
        });
    </script>
@endsection